### ISSUE TITLE
"Action/TaskAssignDateToUndated.php" Isn't packaged in the one click install zip

### ISSUE THREAD

**Issue by iMouath** [dmorlitz/kanboard-TaskAssignDateToUndated#1]
When installing the plugin through the one click install it downloads this zip package
`https://github.com/dmorlitz/kanboard-TaskAssignDateToUndated/blob/2a89f814e78a943a843aaca79125d536e7805ff0/releases/TaskAssignDateToUndated-0.0.1.zip?raw=true`
Which doesn't contain Action/TaskAssignDateToUndated.php, Causing a fatal error.

`2018/09/17 07:12:06 [error] 15#15: *392 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Kanboard\Plugin\TaskAssignDateToUndated\Action\TaskAssignDateToUndated' not found in /var/www/app/plugins/TaskAssignDateToUndated/Plugin.php:9
Stack trace:
#0 /var/www/app/app/Core/Plugin/Loader.php(127): Kanboard\Plugin\TaskAssignDateToUndated\Plugin->initialize()
#1 /var/www/app/app/Core/Plugin/Loader.php(67): Kanboard\Core\Plugin\Loader->initializePlugin('TaskAssignDateT...')
#2 /var/www/app/app/ServiceProvider/PluginProvider.php(27): Kanboard\Core\Plugin\Loader->scan()
#3 /var/www/app/vendor/pimple/pimple/src/Pimple/Container.php(290): Kanboard\ServiceProvider\PluginProvider->register(Object(Pimple\Container))
#4 /var/www/app/app/common.php(58): Pimple\Container->register(Object(Kanboard\ServiceProvider\PluginProvider))
#5 /var/www/app/index.php(6): require('/var/www/app/ap...')
#6 {main}
  thrown in /var/www/app/plugins/TaskAssignDateToUndated/Plugin.php on line 9" while reading response header from upstream, client: 172.18.0.2, server: localhost, request: "GET /?controller=PluginController&action=show HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost"`

Recreating the file solves the error.

**Comment by dmorlitz** [comment]
Thank you for noticing this.  Apparently there was a mistake in the script I use to update GitHub - and the ZIP file was not being made to include files recursively from my development system.  I have corrected this script and re-uploaded the 1-click install ZIP file.

This error actually affected all of my plugins, so I have re-uploaded everyone.

Thank you for pointing this out.
